// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF2EBattleTracker.API.DbContexts;

#nullable disable

namespace PF2EBattleTracker.API.Migrations
{
    [DbContext(typeof(CharacterInfoContext))]
    [Migration("20241219114021_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 3,
                            Name = "Amanda"
                        },
                        new
                        {
                            Id = 2,
                            Level = 3,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Level = 3,
                            Name = "Caitlyn"
                        });
                });

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            Name = "Clumsy",
                            Source = "Spell",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 2,
                            Name = "Off Guard",
                            Source = "Flanked"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 3,
                            Name = "Frightened",
                            Source = "Ghost",
                            Value = 2
                        });
                });

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Condition", b =>
                {
                    b.HasOne("PF2EBattleTracker.API.Entities.Character", "Character")
                        .WithMany("Conditions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Character", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
