// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF2EBattleTracker.API.DbContexts;

#nullable disable

namespace PF2EBattleTracker.API.Migrations
{
    [DbContext(typeof(CharacterInfoContext))]
    [Migration("20250102094331_PF2eTrackerAddedCharacterScores")]
    partial class PF2eTrackerAddedCharacterScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Charisma = 0,
                            Constitution = 0,
                            Dexterity = 0,
                            Intelligence = 0,
                            Level = 3,
                            Name = "Amanda",
                            Strength = 0,
                            Wisdom = 0
                        },
                        new
                        {
                            CharacterId = 2,
                            Charisma = 0,
                            Constitution = 0,
                            Dexterity = 0,
                            Intelligence = 0,
                            Level = 3,
                            Name = "Bob",
                            Strength = 0,
                            Wisdom = 0
                        },
                        new
                        {
                            CharacterId = 3,
                            Charisma = 0,
                            Constitution = 0,
                            Dexterity = 0,
                            Intelligence = 0,
                            Level = 3,
                            Name = "Caitlyn",
                            Strength = 0,
                            Wisdom = 0
                        });
                });

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Condition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("ConditionId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            ConditionId = 1,
                            CharacterId = 1,
                            Name = "Clumsy",
                            Source = "Spell",
                            Value = 1
                        },
                        new
                        {
                            ConditionId = 2,
                            CharacterId = 2,
                            Name = "Off Guard",
                            Source = "Flanked"
                        },
                        new
                        {
                            ConditionId = 3,
                            CharacterId = 3,
                            Name = "Frightened",
                            Source = "Ghost",
                            Value = 2
                        });
                });

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Condition", b =>
                {
                    b.HasOne("PF2EBattleTracker.API.Entities.Character", "Character")
                        .WithMany("Conditions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PF2EBattleTracker.API.Entities.Character", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
